### ISSUE TITLE
Elm-Live not opening browser

### ISSUE THREAD

**Issue by Samatar26** [tomekwi/elm-live#106]
When running `elm-live Main.elm --open --pushstate --output=elm.js` it doesn't open the browser. The server doesn't seem to be running either at localhost:8000. Another interesting thing to note is that when I run elm-reactor I get the following error message: elm-reactor: bind: unsupported operation (Can't assign requested address)

**Comment by Samatar26** [comment]
Seem to be getting this error once in a while too:
```
/usr/local/lib/node_modules/elm-live/source/elm-live.js:163
    server.on('error', (error) => { throw error; });
                                    ^

Error: listen EADDRNOTAVAIL 92.242.132.16:8000
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server.setupListenHandle [as _listen2] (net.js:1288:19)
    at listenInCluster (net.js:1353:12)
    at doListen (net.js:1479:7)
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:84:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:100:10)
```

**Comment by Samatar26** [comment]
Seems to be working now, sorry. No idea what the problem was

**Comment by tomekwi** [comment]
Hey @Samatar26, sorry for the late response. I’m glad the first problem solved itself! Regarding the latter one, if you’re still getting that error, please open a new issue so we can track it down 🙂
