### ISSUE TITLE
elm-live requires Node v6+ to run natively

### ISSUE THREAD

**Issue by sentience** [tomekwi/elm-live#88]
The README says Node 4+ is required to run elm-live natively; however, on both 4.x and 5.x I get this error when running it:

```
/Users/kyank/code/multi-select/node_modules/elm-live/source/debounce.js:4
  let timeout;
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/kyank/code/multi-select/node_modules/elm-live/source/elm-live.js:14:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

Running it with Node v6.x works fine. I suggest updating the README to specify Node v6+ is required.

**Comment by tomekwi** [comment]
Thanks a lot for the heads up, just updated the readme. 🙂
